name: Test Hello World with Unique CSV

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Hello World and Create CSV
        run: |
          # Define a unique filename using date and time
          filename="hello_world_log_$(date +'%Y%m%d_%H%M%S').csv"

          # Create a new CSV file with the message, date, and time
          echo "Message,Date and Time" > $filename
          echo "Hello, world!,$(date)" >> $filename

      - name: Upload CSV log
        uses: actions/upload-artifact@v3
        with:
          name: hello_world_log_${{ github.run_id }}
          path: hello_world_log_*.csv
