name: Test Hello World with Unique CSV in Pacific Time

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # This line is commented out to disable automatic runs
  workflow_dispatch:  # Allows manual run only

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Hello World and Create CSV
        run: |
          export filename="Hello_World_Workflow_Test_$(TZ='America/Los_Angeles' date +'%Y%m%d_%H%M%S').csv"
          echo "Message,Date and Time" > $filename
          echo "Hello, world!,$(TZ='America/Los_Angeles' date)" >> $filename
          echo "filename=$filename" >> $GITHUB_ENV

      - name: Upload CSV log
        uses: actions/upload-artifact@v4
        with:
          name: hello_world_log_${{ github.run_id }}
          path: ${{ env.filename }}
